---

- name: Install Apache web server
  yum: pkg={{ item }} state=installed
  with_items:
     - httpd

- name: Set up httpd
  service: name=httpd enabled=yes

- name: Start the httpd
  service: name=httpd state=started

- name: Create test index.html
  template:
    src: index.html.tpl
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0664

- name: Configure Apache
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: "{{ httpd_configuration }}"
  notify: restart httpd
